language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test travis '' localhost $WP_VERSION

script:
  - cd $TRAVIS_BUILD_DIR
  - |
      composer update
      composer install --dev
      ./vendor/bin/phpunit
